# Generated by Django 4.2.21 on 2025-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningstat',
            name='run_type',
            field=models.CharField(default='training', max_length=50),
        ),
    ]
