# Generated by Django 4.2.21 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_runningstat_run_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningstat',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
