# Generated by Django 4.2.21 on 2025-05-14 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_runningstat_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningstat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
