# Generated by Django 4.2.21 on 2025-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
