# Generated by Django 4.2.21 on 2025-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_remove_challenge_user_challenge_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningstat',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningstat',
            name='heart_rate_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
