name: mobile
description: Un projet Flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^14.0.0
  cupertino_icons: ^1.0.2

flutter:
  assets:
    - assets/image/running.png

environment:
  sdk: "^3.7.0"
