# Generated by Django 4.2.21 on 2025-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_firebaseusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='firebaseusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='firebaseusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
